api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: true
      targetPort: {{ targetPortOrDefault 8080 }}
      transport: http
      allowInsecure: false
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--secrets
        value: '{{ .Env.SECRETS_VAULTURI }}'
      - name: connectionstrings--tokencache
        value: '{{ .Env.TOKENCACHE_CONNECTIONSTRING }}'
  template:
    containers:
      - image: {{ .Image }}
        name: authservice
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: ENTRAIDAPP__APPAUTHDOMAIN
            value: '{{ parameter "ENTRAIDAPP_APPAUTHDOMAIN" }}'
          - name: ENTRAIDAPP__CALLBACKPATH
            value: '{{ parameter "ENTRAIDAPP_CALLBACKPATH" }}'
          - name: ENTRAIDAPP__CLIENTID
            value: '{{ parameter "ENTRAIDAPP_CLIENTID" }}'
          - name: ENTRAIDAPP__DOMAIN
            value: '{{ parameter "ENTRAIDAPP_DOMAIN" }}'
          - name: ENTRAIDAPP__INSTANCE
            value: '{{ parameter "ENTRAIDAPP_INSTANCE" }}'
          - name: ENTRAIDAPP__TENANTID
            value: '{{ parameter "ENTRAIDAPP_TENANTID" }}'
          - name: GITHUBAPP__APPAUTHDOMAIN
            value: '{{ parameter "GITHUBAPP_APPAUTHDOMAIN" }}'
          - name: GITHUBAPP__CALLBACKPATH
            value: '{{ parameter "GITHUBAPP_CALLBACKPATH" }}'
          - name: GITHUBAPP__CLIENTID
            value: '{{ parameter "GITHUBAPP_CLIENTID" }}'
          - name: GITHUBAPP__CLIENTID__DEV
            value: '{{ parameter "GITHUBAPP_CLIENTID_DEV" }}'
          - name: GITHUBAPP__INSTANCE
            value: '{{ parameter "GITHUBAPP_INSTANCE" }}'
          - name: GITHUBAPP__ISSUER
            value: '{{ parameter "GITHUBAPP_ISSUER" }}'
          - name: HTTP_PORTS
            value: '{{ targetPortOrDefault 0 }}'
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: ConnectionStrings__secrets
            secretRef: connectionstrings--secrets
          - name: ConnectionStrings__tokenCache
            secretRef: connectionstrings--tokencache
    scale:
      minReplicas: 1
tags:
  azd-service-name: authservice
  aspire-resource-name: authservice
