@AuthService_HostAddress = http://localhost:5132

POST {{AuthService_HostAddress}}/token
Accept: application/json

grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&subject_token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImU3ZThhN2Q1LTUwMGQtNWU4NS1iY2U3LWZkMTVjODgxYzFhMSIsInR5cCI6IkpXVCIsIng1dCI6ImhaZFprVWN5eE5NTjAzWjY0dkpJTnlpUS1RVSJ9.eyJhY3QiOnsic3ViIjoiaHR0cHM6Ly9hcGkuZ2l0aHViY29waWxvdC5jb20ifSwiYXVkIjoiSXYyM2xpQjNLQ2xDeXlDUUVuUUwiLCJleHAiOjE3NDI0MjI5ODksImlhdCI6MTc0MjQwMTM4OSwiaXNzIjoiaHR0cHM6Ly9naXRodWIuY29tL2xvZ2luL29hdXRoIiwibmJmIjoxNzQyNDAxMDg5LCJzdWIiOiIyOTAxMDI4MyJ9.Ur6Lzf5g8d4QvqUH2izXd2T3gfSEKmkOWPwFw7_14Akpb4_sv5t7j64ou5ZqWjaBv28YGqP3t38lRqEqDhwXWHcoQBlWi5BQwlU-wZUNZsyuz-AtPzkt5cZ8TuBgogsNTdAMSPgolg0ZND8rmNtvcOYibN9402ezdih5qZ5HSUQstsb8UebhJ246plnwZS3q8hbt449qMkGN9kKQReaDzkhCq9I3duBcLjIZQ0E5Qm-XJ9IT_N-letaKG1JiFcItpD6O3tB7HxVAFL118xROFPzzA4St_2KLBrp6aIpHfupRPwinBEpfverjpc7LseuHTYhaDsoSC3A4mcBrZC_mJQ&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aid_token