# This workflow builds, tests, and deploys the project using azd for Azure deployment
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/GHCPEAZDO.sln

      - name: Build
        run: dotnet build ./src/GHCPEAZDO.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test ./src/GHCPEAZDO.sln --no-build --verbosity normal

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install Azure Developer CLI (azd)
        uses: azure/setup-azd@v2

      - name: Authenticate with Azure using azd and OIDC
        run: |
          azd auth login --tenant-id ${{ secrets.AZURE_TENANT_ID }} --client-id ${{ secrets.AZURE_CLIENT_ID }} --federated-credential-provider github
          azd config set defaults.subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Provision Infrastructure
        run: azd provision --no-prompt
        env:
          ## Define the additional variables or secrets that are required only for provision
          ENTRAIDAPP_CLIENTID: ${{ vars.ENTRAIDAPP_CLIENTID }}
          ENTRAIDAPP_TENANTID: ${{ vars.ENTRAIDAPP_TENANTID }}
          GITHUBAPP_CLIENTID: ${{ vars.GITHUBAPP_CLIENTID }}

      - name: Deploy Application
        run: azd deploy --no-prompt
        env:
          ## Define the additional variables or secrets that are required only for deploy
          ENTRAIDAPP_CLIENTID: ${{ vars.ENTRAIDAPP_CLIENTID }}
          ENTRAIDAPP_TENANTID: ${{ vars.ENTRAIDAPP_TENANTID }}
          GITHUBAPP_CLIENTID: ${{ vars.GITHUBAPP_CLIENTID }}
